language: racket

env: 
- RACKET_VERSION=6.5

sudo: required

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash 

script: 
- pwd
- ls
- /usr/racket/bin/raco test -r Racket/all-tests.rkt
- lein deps && lein sub -s "rosetta" do deps, clean, test 

after_success: 
  - cd rosetta ; lein cloverage --codecov 
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

