language: racket

env: 
- RACKET_VERSION=6.5

sudo: required

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash 
- which racket
- racket -v

script: 
- pwd
- ls
- raco test -r Racket/sorting-test.rkt
